### ISSUE TITLE
Can't see props if js comes from node_modules

### ISSUE THREAD

**Issue by szafran89** [pocka/storybook-addon-vue-info#104]
I not sure if it's a bug or sth to configure.

If my js file comes from node_modules I can't see props table. I tried to set an alias for `node_module` but the same result.
Do you have a clue why it happens?

My code:
```
<template src="./Badge.html" />

<script>
import Badge from '../../../../node_modules/@package/name/src/atoms/badge/Badge.js'
// The same if I set alias or path like this `@package/name/src/atoms/badge/Badge.js`

export default {
  mixins: [Badge]
}
</script>
```

**To Reproduce**
Move js file to node_modules

**Expected behavior**
See props table

**Versions**

- `storybook-addon-vue-info`: "^1.2.1"
- `@storybook/vue`: "5.1.3"

**Comment by pocka** [comment]
@szafran89 
Are you using `vue-docgen-api` through `storybook-addon-vue-info/loader`? If so, this is the docgen's problem.

For runtime props parsing (no-docgen way), mixins are not supported.

**Comment by bezany** [comment]
@szafran89 Hello! I had same problem. Look like  vue-docgen-api ignore mixins from node_modules, see vue-styleguidist/vue-styleguidist#417
I simple moved code to another folder.

**Comment by pocka** [comment]
Thanks to @bezany for examining the problem!

As [the PR](https://github.com/vue-styleguidist/vue-styleguidist/pull/417) describes, it seems to be the default behavior of vue-docgen-api (I'm not sure why they don't parse the files inside node_modules though...). I'm closing this because it's an *expected result*, but if you have an opinion or problems, please submit an issue on [vue-styleguidist/vue-styleguidist](https://github.com/vue-styleguidist/vue-styleguidist).
