### ISSUE TITLE
Add description tab on property table

### ISSUE THREAD

**Issue by Zelig880** [pocka/storybook-addon-vue-info#20]
It would be very beneficial to have the ability to add a "descrition" field on the Components tabs.

This could be achieved by allowing developers to define a JS Docs comments on each of the property.

The approach may be similar to the one taken by react-styleguidist.

I am happy to help developing it if it is part of your roadmap

**Comment by pocka** [comment]
Yes, it would be great! I'll take a look at https://github.com/mihalik/react-storybook-addon-docgen to make a decision whether this feature could be implmented.

**Comment by pocka** [comment]
Official info addon for react uses https://github.com/storybooks/babel-plugin-react-docgen which is loaded in [`package.json` in `@storybook/react`](https://github.com/storybooks/storybook/blob/9bbe5cc405bf5cce1c55c81147c13d75c95892b3/app/react/package.json#L38).
It appends additional information (e.g. jsdoc comment) for components while compile time.

If we implement this feature, we need to...

- write something like `babel-plugin-vue-docgen` (I don't know this is possible or not...)
- add it to `package.json` of `@storybook/vue` or enforce to require it for users
- read `Component.__docgenInfo` in runtime

# Conclusion

Considering benefits, it requires too much effort to implement this feature.
You can use https://github.com/vue-styleguidist/vue-styleguidist instead of storybook.
