### ISSUE TITLE
Disable style default ?

### ISSUE THREAD

**Issue by florinesueur** [pocka/storybook-addon-vue-info#21]
i use a global style scss.

**Comment by pocka** [comment]
Could you provide more detail?

**Comment by AudeFi** [comment]
I reopen this issue for the same question. 

Is it possible to disable your default style and create my own file. 
It's mainly because of the preview section style. 

I could use previewClassName property, but the `all: initial` in your CSS is a bit annoying since I breaks some of my components, like the body font-family that is ignored

**Comment by pocka** [comment]
@AudeFi 

> Is it possible to disable your default style and create my own file.
> It's mainly because of the preview section style.

You can't remove styles which added by the addon.

> I could use previewClassName property, but the `all: initial` in your CSS is a bit annoying since I breaks some of my components, like the body font-family that is ignored

Yes... I think I took a mistake. I should have applied `all: initial` to the addon's own components (e.g. props table) instead of preview then make it opt-out-able.

IMO, It's not difficult to rewrite all styles; There are just 10 components!
Though I'll fix this in a not-so-far future release, PRs are always welcome and I'll check them ASAP.

**Comment by pocka** [comment]
Fixed in v1.3.2
