### ISSUE TITLE
Vue-info breaks knob addon

### ISSUE THREAD

**Issue by wprogLK** [pocka/storybook-addon-vue-info#75]
**Describe the bug**
@pocka I really like your addon, however there seems to be a problem.

The storybook knobs addon seems not to work with the vue-info addon. When changing a prop by using a knob it has no effect on the rendered component's prop.

Currently I'm using vue-info version 1.0.0-beta.0, knobs 4.1.11 together with storybook version 4.1.11.

**To Reproduce**
_.storybook/addons.js_
`import 'storybook-addon-vue-info/lib/register'`
`import '@storybook/addon-knobs/register';`

_.storybook/config.js_
`import { configure, addDecorator   } from "@storybook/vue";`
`import { withKnobs } from '@storybook/addon-knobs';`
`import { withInfo } from 'storybook-addon-vue-info'`
`import Vue from "vue";`
`import Vuex from "vuex";`
`Vue.use(Vuex);`
`const req = require.context('../src/components', true, /\.story\.js$/)`
`function loadStories() {`
  `req.keys().forEach((filename) => req(filename))`
`}`
`addDecorator(withInfo);`
`addDecorator(withKnobs);`
`configure(loadStories, module);`

_/src/components/Label.vue_

`<template>`
`  <p>Hello{{ description }}</p>`
`</template>`
`<script>`
`import Vue from 'vue'`
`export default Vue.extend({`
`	props: {`
`		description: {`
`			type: Text,`
`			default: 'Hello'`
`		}`
`	}`
`})`
`</script>`

_/src/components/Label.story.vue_

`import { storiesOf } from '@storybook/vue'`
`import { text } from '@storybook/addon-knobs'`
`import Label from './Label.vue'`
`storiesOf('Wizard', module).add(`
`	'with info and knobs',`
`	() => ({`
`		components: { Label },`
`		props: {`
`			description: {`
`				type: String,`
`				default: text('Description', 'This should work.')`
`			}`
`		},`
`		template: '<Label :description="description"/>'`
`	}),`
`	{`
`		info: {}`
`	}`
`)`

**Expected behavior**
When changing a prop via knob the related prop should be changed and rerendered.

**Comment by pocka** [comment]
`@storybook/vue@4.1.x` has an issue with story decorators and knobs addon (https://github.com/storybooks/storybook/issues/5048). That issue was fixed in `@storybook/vue@4.2.0-alpha.6`.

[Our example](https://deploy-preview-66--storybook-addon-vue-info.netlify.com/?selectedKind=Compatibilities%2F%40storybook%2Faddon-knobs&selectedStory=panel&full=0&addons=1&stories=1&panelRight=1&addonPanel=STORYBOOK_ADDON_VUE_INFO%2Fpanel&https%3A%2F%2Fdeploy-preview-66--storybook-addon-vue-info.netlify.com%2F%3FselectedKind=Examples%2FBasic%20usage) uses `@storybook/vue@4.2.0-alpha.11` FYI. Please try `>= @storybook/vue@4.2.0-alpha.6`
