### ISSUE TITLE
Missing slots, props, description for splitted components

### ISSUE THREAD

**Issue by szafran89** [pocka/storybook-addon-vue-info#83]
Hi,

I have one question. My vue component is splitted to multiple files, in this case there are missing events/slots and description generated from comments. Below simple example.

```
<template src="./Label.html" />

<script>
  import instance from "./Label.js"

  export default {
    ...instance
  }
</script>

<style lang="scss" src="./Label.scss"/>
```
![image](https://user-images.githubusercontent.com/5370251/55067506-2945ff80-5080-11e9-9523-3e1978f04e19.png)

Is there any option adjust it in my storybook's webpack config or other way to make it working. 

BTW.  I like this addon so much.

Thanks in advance!

**Comment by pocka** [comment]
@szafran89 
It seems that vue-docgen-api fails to parse your component. If you set custom loader correctly, it's a problem in custom loader or vue-docgen-api.

Since I found that it's too difficult to debug vue-docgen-api related things, I'd like to add `console.error` or `console.warn` for the time when it failed to parse components.

> Is there any option adjust it in my storybook's webpack config or other way to make it working.

At least there is no workaround in storybook' webpack config. The custom loader doesn't take any options for vue-docgen-api (I know this isn't good API, will be improved in the future).
At first glance, I thought to change codes inside `<script>` tag may fix the issue, but I'm not sure now...

**Comment by szafran89** [comment]
Thank you very much @pocka ;) Your advice fixed my issue. I don't know why I didn't try it before 🤦‍♂️
